flowchart TD
%% class definitions
classDef subgraphClass fill:#f2f2f2,stroke:#333,stroke-width:2px;
classDef basicNode fill:#e6f7ff,stroke:#0050b3,stroke-width:1px;
classDef branchNode fill:#fff7e6,stroke:#ad6800,stroke-width:1px;
classDef jumpNode fill:#f9f0ff,stroke:#531dab,stroke-width:1px;
classDef sceneMoveNode fill:#fff0f6,stroke:#c41d7f,stroke-width:1px;
classDef textNode fill:#f6ffed,stroke:#237804,stroke-width:1px;
linkStyle default stroke:#8a2be2,stroke-width:1px;
subgraph SG01["　"]
end
subgraph SG02["　"]
end
subgraph SG03["　"]
end
subgraph SG04["　"]
end
subgraph SG05["　"]
end
subgraph SG06["　"]
end
subgraph SG07["　"]
end
subgraph SG08["　"]
end
subgraph SG09["　"]
end
subgraph SG10["　"]
end
subgraph SG11["　"]
end
subgraph SG12["　"]
end
subgraph SG13["　"]
end
subgraph SG14["　"]
end
subgraph SG15["　"]
end
subgraph SG16["　"]
end
subgraph SG17["　"]
end
subgraph SG18["　"]
end
subgraph SG19["　"]
end
subgraph SG20["　"]
end
subgraph SG21["　"]
end
subgraph SG22["　"]
end
subgraph SG23["　"]
end
subgraph SG24["　"]
end
subgraph SG25["　"]
end
subgraph SG26["　"]
end
subgraph SG27["　"]
end
subgraph SG28["　"]
end
subgraph SG29["　"]
end
subgraph SG30["　"]
end
subgraph SG31["　"]
end
subgraph SG32["　"]
end
subgraph SG33["　"]
end
subgraph SG34["　"]
end
subgraph SG35["　"]
end
subgraph SG36["　"]
end
subgraph SG37["　"]
end
subgraph SG38["　"]
end
subgraph SG39["　"]
end
subgraph SG40["　"]
end
subgraph SG41["　"]
end
subgraph SG42["　"]
end
subgraph SG43["　"]
end
subgraph SG44["　"]
end
subgraph SG45["　"]
end
subgraph SG46["　"]
end
TITLE_01["アプリを開いたとき"]
N0001["1. 端末にログイン情報が残っている場合は段落2-1に移動する。端末にログイン情報が残っていない場合は段落3-1に移動する。。"]
N0002["1. 端末にログイン情報が残っている場合は段落2-1に移動する。"]
N0003["1. 端末にログイン情報が残っていない場合は段落3-1に移動する。"]
N0004["2-1. ローディング画面を表示する。"]
N0005["2-2. ローディング画面を閉じる。"]
N0006["2-3. ホーム画面に移動する。"]
N0007["2-4. シーン「ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき）」の1.〜7.と同様。"]
N0008["3-1. ログイン画面に移動する。"]
N0009["3-2. ログインID・パスワードを入力する欄が表示される。"]
N0010["3-3. 「ログイン」ボタンを押したとき、シーン「ログインボタンを押したとき」に移動する。「利用規約」ボタンを押したとき、シーン「利用規約ボタンを押したとき（呼び出し元：ログイン画面）」に移動する。。"]
N0011["3-3. 「ログイン」ボタンを押したとき、シーン「ログインボタンを押したとき」に移動する。"]
N0012["3-3. 「利用規約」ボタンを押したとき、シーン「利用規約ボタンを押したとき（呼び出し元：ログイン画面）」に移動する。"]
TITLE_02["ログインボタンを押したとき"]
N0013["1. 入力されたログイン情報が間違っている場合は段落2-1に移動する。入力されたログイン情報があっている場合は段落3-1に移動する。。"]
N0014["1. 入力されたログイン情報が間違っている場合は段落2-1に移動する。"]
N0015["1. 入力されたログイン情報があっている場合は段落3-1に移動する。"]
N0016["2-1. ログイン情報が間違っている旨が表示される。"]
N0017["2-2. ログイン情報をユーザーが修正し、「ログイン」ボタンを押した場合はこのシーンの最初に移動する。「利用規約」ボタンを押した場合はシーン「利用規約ボタンを押したとき（呼び出し元：ログイン画面）」に移動する。。"]
N0018["2-2. ログイン情報をユーザーが修正し、「ログイン」ボタンを押した場合はこのシーンの最初に移動する。"]
N0019["2-2. 「利用規約」ボタンを押した場合はシーン「利用規約ボタンを押したとき（呼び出し元：ログイン画面）」に移動する。"]
N0020["3-1. ローディング画面を表示する。"]
N0021["3-2. ローディング画面を閉じる。"]
N0022["3-3. ホーム画面に移動する。"]
N0023["3-4. シーン「ホーム画面の各アイコンを押したとき（呼び出し元：ログインボタンを押したとき）」の1.〜7.と同様。"]
TITLE_03["ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき）"]
N0024["1. ホーム画面に「カルテ新規入力」「カルテ検索」「患者マスタ」「アカウント管理」の4つのアイコンのみが表示される。"]
N0025["2. ヘッダーにシステムロゴとハンバーガーメニューが表示される。"]
N0026["3. ハンバーガーメニューを押したとき、シーン「ハンバーガーメニューを押したとき」に移動する。ヘッダーのシステムロゴを押したとき、このシーンの段落1に移動する。。"]
N0027["3. ハンバーガーメニューを押したとき、シーン「ハンバーガーメニューを押したとき」に移動する。"]
N0028["3. ヘッダーのシステムロゴを押したとき、このシーンの段落1に移動する。"]
N0029["4. 「カルテ新規入力」アイコンを押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。"]
N0030["5. 「カルテ検索」アイコンを押したとき、シーン「カルテ検索アイコンを押したとき」に移動する。"]
N0031["6. 「患者マスタ」アイコンを押したとき、シーン「患者マスタアイコンを押したとき」に移動する。"]
N0032["7. 「アカウント管理」アイコンを押したとき、シーン「アカウント管理アイコンを押したとき」に移動する。ユーザー権限が入力者または閲覧者の場合、「アカウント管理」アイコンは非表示となり、押下不能である。"]
TITLE_04["ホーム画面の各アイコンを押したとき（呼び出し元：ログインボタンを押したとき）"]
N0033["1. シーン「ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき）」の1.〜7.と同様。"]
TITLE_05["ハンバーガーメニューを押したとき"]
N0034["1. 画面全体を覆うハンバーガーメニューが表示され、メニュー外の操作ができなくなる。"]
N0035["2. メニューに「カルテ新規入力」「カルテ検索」「患者マスタ」「アカウント管理」「ログイン情報変更」「使用履歴」「利用規約」「ログアウト」が表示される。"]
N0036["3. 「カルテ新規入力」を押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。"]
N0037["4. 「カルテ検索」を押したとき、シーン「カルテ検索アイコンを押したとき」に移動する。"]
N0038["5. 「患者マスタ」を押したとき、シーン「患者マスタアイコンを押したとき」に移動する。"]
N0039["6. 「アカウント管理」を押したとき、シーン「アカウント管理アイコンを押したとき」に移動する。ユーザー権限が入力者または閲覧者の場合、「アカウント管理」は非表示となり、押下不能である。"]
N0040["7. 「ログイン情報変更」を押したとき、シーン「ログイン情報変更ボタンを押したとき」に移動する。"]
N0041["8. 「使用履歴」を押したとき、シーン「使用履歴ボタンを押したとき」に移動する。"]
N0042["9. 「利用規約」を押したとき、シーン「利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー）」に移動する。"]
N0043["10. 「ログアウト」を押したとき、シーン「ログアウトボタンを押したとき」に移動する。"]
TITLE_06["利用規約ボタンを押したとき（呼び出し元：ログイン画面）"]
N0044["1. 利用規約画面に移動する。"]
N0045["2. 利用規約の本文が表示される。"]
N0046["3. 「戻る」ボタンを押したとき、シーン「ログイン画面に戻るボタンを押したとき」に移動する。"]
TITLE_07["ログイン画面に戻るボタンを押したとき"]
N0047["1. ログイン画面に移動する。"]
N0048["2. ログインID・パスワードを入力する欄が表示される。"]
N0049["3. 「ログイン」ボタンを押したとき、シーン「ログインボタンを押したとき」に移動する。「利用規約」ボタンを押したとき、シーン「利用規約ボタンを押したとき（呼び出し元：ログイン画面）」に移動する。。"]
N0050["3. 「ログイン」ボタンを押したとき、シーン「ログインボタンを押したとき」に移動する。"]
N0051["3. 「利用規約」ボタンを押したとき、シーン「利用規約ボタンを押したとき（呼び出し元：ログイン画面）」に移動する。"]
TITLE_08["利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー）"]
N0052["1. 利用規約画面に移動する。"]
N0053["2. 利用規約の本文が表示される。"]
N0054["3. 「戻る」ボタンを押したとき、シーン「ハンバーガーメニューに戻るボタンを押したとき」に移動する。"]
TITLE_09["ハンバーガーメニューに戻るボタンを押したとき"]
N0055["1. ハンバーガーメニューが表示された状態に戻る。"]
N0056["2. シーン「ハンバーガーメニューを押したとき」の2.〜10.と同様。"]
TITLE_10["ログアウトボタンを押したとき"]
N0057["1. ログアウト確認ダイアログを表示する。"]
N0058["2. 「はい」を押したとき、段落3-1に移動する。「いいえ」を押したとき、段落4-1に移動する。。"]
N0059["2. 「はい」を押したとき、段落3-1に移動する。"]
N0060["2. 「いいえ」を押したとき、段落4-1に移動する。"]
N0061["3-1. ローディング画面を表示する。"]
N0062["3-2. ローディング画面を閉じる。"]
N0063["3-3. ログイン画面に移動する。"]
N0064["3-4. シーン「ログイン画面に戻るボタンを押したとき」の2.〜3.と同様。"]
N0065["4-1. ログアウト確認ダイアログを閉じる。"]
N0066["4-2. シーン「ハンバーガーメニューを押したとき」の2.〜10.と同様。"]
TITLE_11["ログイン情報変更ボタンを押したとき"]
N0067["1. ログイン情報変更画面に移動する。"]
N0068["2. 現在のパスワード・新しいパスワード・新しいパスワード（確認）を入力する欄が表示される。"]
N0069["3. 「変更する」ボタンを押したとき、シーン「ログイン情報変更の変更するボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0070["3. 「変更する」ボタンを押したとき、シーン「ログイン情報変更の変更するボタンを押したとき」に移動する。"]
N0071["3. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
TITLE_12["ホーム画面に戻るボタンを押したとき"]
N0072["1. ホーム画面に移動する。"]
N0073["2. シーン「ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき）」の1.〜7.と同様。"]
TITLE_13["ログイン情報変更の変更するボタンを押したとき"]
N0074["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。入力内容に問題がない場合は段落3-1に移動する。。"]
N0075["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0076["1. 入力内容に問題がない場合は段落3-1に移動する。"]
N0077["2-1. 入力エラーを表示する。"]
N0078["2-2. 入力内容を修正し「変更する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0079["2-2. 入力内容を修正し「変更する」ボタンを押したとき、このシーンの最初に移動する。"]
N0080["2-2. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
N0081["3-1. 変更確認ダイアログを表示する。"]
N0082["3-2. 「はい」を押したとき、段落4-1に移動する。「いいえ」を押したとき、段落5-1に移動する。。"]
N0083["3-2. 「はい」を押したとき、段落4-1に移動する。"]
N0084["3-2. 「いいえ」を押したとき、段落5-1に移動する。"]
N0085["4-1. ローディング画面を表示する。"]
N0086["4-2. ローディング画面を閉じる。"]
N0087["4-3. 変更完了のメッセージが表示される。"]
N0088["4-4. 「OK」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
N0089["5-1. 変更確認ダイアログを閉じる。"]
N0090["5-2. シーン「ログイン情報変更ボタンを押したとき」の2.〜3.と同様。"]
TITLE_14["カルテ新規入力アイコンを押したとき"]
N0091["1. カルテ新規入力画面に移動する。"]
N0092["2. 患者マスタの選択方法として「既存患者を選択」「新規患者を登録」を切り替えるタブが表示される。"]
N0093["3. 「既存患者を選択」タブを押したとき、シーン「カルテ新規入力：既存患者タブを押したとき」に移動する。「新規患者を登録」タブを押したとき、シーン「カルテ新規入力：新規患者タブを押したとき」に移動する。。"]
N0094["3. 「既存患者を選択」タブを押したとき、シーン「カルテ新規入力：既存患者タブを押したとき」に移動する。"]
N0095["3. 「新規患者を登録」タブを押したとき、シーン「カルテ新規入力：新規患者タブを押したとき」に移動する。"]
TITLE_15["カルテ新規入力：既存患者タブを押したとき"]
N0096["1. 患者マスタ検索欄（患者ID、氏名、生年月日、電話番号）と検索ボタンが表示される。"]
N0097["2. 検索結果テーブルに患者ID、氏名、生年月日、性別、電話番号が表示される。並び替え機能、削除済み表示切替、検索結果のうち30件のみ表示、続きを表示ボタンが表示される。"]
N0098["3. 患者を選択したとき、患者情報がカルテ入力欄に自動入力される。"]
N0099["4. カルテ入力欄に、受診日、診療科、保険会社、保険項目、診療内容、請求金額など、保険請求書類に必要な入力欄が表示される。"]
N0100["5. 「登録する」ボタンを押したとき、シーン「カルテ登録ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0101["5. 「登録する」ボタンを押したとき、シーン「カルテ登録ボタンを押したとき」に移動する。"]
N0102["5. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
TITLE_16["カルテ新規入力：新規患者タブを押したとき"]
N0103["1. 新規患者登録欄に患者ID、生年月日、苗字、名前、性別、住所、電話番号などの入力欄が表示される。"]
N0104["2. カルテ入力欄に、受診日、診療科、保険会社、保険項目、診療内容、請求金額など、保険請求書類に必要な入力欄が表示される。"]
N0105["3. 「登録する」ボタンを押したとき、シーン「カルテ登録ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0106["3. 「登録する」ボタンを押したとき、シーン「カルテ登録ボタンを押したとき」に移動する。"]
N0107["3. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
TITLE_17["カルテ登録ボタンを押したとき"]
N0108["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。新規患者タブの場合で、患者IDが同グループ内で重複している場合は段落3-1に移動する。生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。入力内容に問題がない場合は段落5-1に移動する。。"]
N0109["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0110["1. 新規患者タブの場合で、患者IDが同グループ内で重複している場合は段落3-1に移動する。"]
N0111["1. 生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。"]
N0112["1. 入力内容に問題がない場合は段落5-1に移動する。"]
N0113["2-1. 入力エラーを表示する。"]
N0114["2-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。。"]
N0115["2-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。"]
N0116["2-2. 「戻る」ボタンを押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。"]
N0117["3-1. 患者IDが重複している旨のエラーが表示される。"]
N0118["3-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。。"]
N0119["3-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。"]
N0120["3-2. 「戻る」ボタンを押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。"]
N0121["4-1. 類似患者が存在する旨の警告ダイアログを表示する。"]
N0122["4-2. ダイアログ内に類似候補の患者ID・氏名・生年月日が一覧表示される。"]
N0123["4-3. 「このまま登録する」を押したとき段落5-1に移動する。「戻る」を押したとき段落6-1に移動する。。"]
N0124["4-3. 「このまま登録する」を押したとき段落5-1に移動する。"]
N0125["4-3. 「戻る」を押したとき段落6-1に移動する。"]
N0126["5-1. 登録確認ダイアログを表示する。"]
N0127["5-2. 「はい」を押したとき段落7-1に移動する。「いいえ」を押したとき段落6-1に移動する。。"]
N0128["5-2. 「はい」を押したとき段落7-1に移動する。"]
N0129["5-2. 「いいえ」を押したとき段落6-1に移動する。"]
N0130["6-1. ダイアログを閉じる。"]
N0131["6-2. シーン「カルテ新規入力：新規患者タブを押したとき」の1.〜3.またはシーン「カルテ新規入力：既存患者タブを押したとき」の1.〜5.と同様。"]
N0132["7-1. ローディング画面を表示する。"]
N0133["7-2. ローディング画面を閉じる。"]
N0134["7-3. 登録完了のメッセージが表示される。"]
N0135["7-4. 「OK」ボタンを押したとき、シーン「カルテ新規入力アイコンを押したとき」に移動する。"]
TITLE_18["カルテ検索アイコンを押したとき"]
N0136["1. カルテ検索画面に移動する。"]
N0137["2. 検索欄に患者ID、氏名、受診日、保険会社、保険項目、カルテ作成者、削除済み表示切替が表示される。"]
N0138["3. 「検索」ボタンを押したとき、段落4-1に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0139["3. 「検索」ボタンを押したとき、段落4-1に移動する。"]
N0140["3. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
N0141["4-1. カルテ検索結果テーブルに、カルテID、患者ID、氏名、受診日、保険会社、保険項目、作成者、削除状態が表示される。"]
N0142["4-2. 並び替え機能、検索結果のうち30件のみ表示、続きを表示ボタンが表示される。"]
N0143["4-3. 各行に「詳細」「編集」「削除」「復活」「保険請求書類を選択」ボタンが表示される。ユーザー権限が閲覧者の場合「編集」「削除」「復活」ボタンは非表示となり、押下不能である。ユーザー権限が入力者の場合「削除」「復活」ボタンは非表示となり、押下不能である。削除済みの行にのみ「復活」ボタンが表示される。"]
N0144["4-4. 「詳細」ボタンを押したとき、シーン「カルテ詳細ボタンを押したとき」に移動する。「編集」ボタンを押したとき、シーン「カルテ編集ボタンを押したとき」に移動する。「削除」ボタンを押したとき、シーン「カルテ削除ボタンを押したとき」に移動する。「復活」ボタンを押したとき、シーン「カルテ復活ボタンを押したとき」に移動する。「保険請求書類を選択」ボタンを押したとき、シーン「保険請求書類を選択ボタンを押したとき」に移動する。。"]
N0145["4-4. 「詳細」ボタンを押したとき、シーン「カルテ詳細ボタンを押したとき」に移動する。"]
N0146["4-4. 「編集」ボタンを押したとき、シーン「カルテ編集ボタンを押したとき」に移動する。"]
N0147["4-4. 「削除」ボタンを押したとき、シーン「カルテ削除ボタンを押したとき」に移動する。"]
N0148["4-4. 「復活」ボタンを押したとき、シーン「カルテ復活ボタンを押したとき」に移動する。"]
N0149["4-4. 「保険請求書類を選択」ボタンを押したとき、シーン「保険請求書類を選択ボタンを押したとき」に移動する。"]
TITLE_19["カルテ詳細ボタンを押したとき"]
N0150["1. カルテ詳細画面に移動する。"]
N0151["2. カルテの入力内容と紐づく患者マスタ情報が表示される。"]
N0152["3. 「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_20["カルテ編集ボタンを押したとき"]
N0153["1. カルテ編集画面に移動する。"]
N0154["2. 既存のカルテ内容が入力欄に表示され、患者マスタの選択方法として「既存患者を選択」「新規患者を登録」を切り替えるタブが表示される。"]
N0155["3. 「既存患者を選択」タブを押したとき、シーン「カルテ編集：既存患者タブを押したとき」に移動する。「新規患者を登録」タブを押したとき、シーン「カルテ編集：新規患者タブを押したとき」に移動する。。"]
N0156["3. 「既存患者を選択」タブを押したとき、シーン「カルテ編集：既存患者タブを押したとき」に移動する。"]
N0157["3. 「新規患者を登録」タブを押したとき、シーン「カルテ編集：新規患者タブを押したとき」に移動する。"]
TITLE_21["カルテ編集：既存患者タブを押したとき"]
N0158["1. シーン「カルテ新規入力：既存患者タブを押したとき」の1.〜4.と同様。"]
N0159["2. 「更新する」ボタンを押したとき、シーン「カルテ更新ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。。"]
N0160["2. 「更新する」ボタンを押したとき、シーン「カルテ更新ボタンを押したとき」に移動する。"]
N0161["2. 「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_22["カルテ編集：新規患者タブを押したとき"]
N0162["1. シーン「カルテ新規入力：新規患者タブを押したとき」の1.〜2.と同様。"]
N0163["2. 「更新する」ボタンを押したとき、シーン「カルテ更新ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。。"]
N0164["2. 「更新する」ボタンを押したとき、シーン「カルテ更新ボタンを押したとき」に移動する。"]
N0165["2. 「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_23["カルテ更新ボタンを押したとき"]
N0166["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。新規患者タブの場合で、患者IDが同グループ内で重複している場合は段落3-1に移動する。生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。入力内容に問題がない場合は段落5-1に移動する。。"]
N0167["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0168["1. 新規患者タブの場合で、患者IDが同グループ内で重複している場合は段落3-1に移動する。"]
N0169["1. 生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。"]
N0170["1. 入力内容に問題がない場合は段落5-1に移動する。"]
N0171["2-1. 入力エラーを表示する。"]
N0172["2-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「カルテ編集ボタンを押したとき」に移動する。。"]
N0173["2-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。"]
N0174["2-2. 「戻る」ボタンを押したとき、シーン「カルテ編集ボタンを押したとき」に移動する。"]
N0175["3-1. 患者IDが重複している旨のエラーが表示される。"]
N0176["3-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「カルテ編集ボタンを押したとき」に移動する。。"]
N0177["3-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。"]
N0178["3-2. 「戻る」ボタンを押したとき、シーン「カルテ編集ボタンを押したとき」に移動する。"]
N0179["4-1. 類似患者が存在する旨の警告ダイアログを表示する。"]
N0180["4-2. ダイアログ内に類似候補の患者ID・氏名・生年月日が一覧表示される。"]
N0181["4-3. 「このまま更新する」を押したとき段落5-1に移動する。「戻る」を押したとき段落6-1に移動する。。"]
N0182["4-3. 「このまま更新する」を押したとき段落5-1に移動する。"]
N0183["4-3. 「戻る」を押したとき段落6-1に移動する。"]
N0184["5-1. 更新確認ダイアログを表示する。"]
N0185["5-2. 「はい」を押したとき段落7-1に移動する。「いいえ」を押したとき段落6-1に移動する。。"]
N0186["5-2. 「はい」を押したとき段落7-1に移動する。"]
N0187["5-2. 「いいえ」を押したとき段落6-1に移動する。"]
N0188["6-1. ダイアログを閉じる。"]
N0189["6-2. シーン「カルテ編集：新規患者タブを押したとき」の1.〜2.またはシーン「カルテ編集：既存患者タブを押したとき」の1.〜2.と同様。"]
N0190["7-1. ローディング画面を表示する。"]
N0191["7-2. ローディング画面を閉じる。"]
N0192["7-3. 更新完了のメッセージが表示される。"]
N0193["7-4. 「OK」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_24["カルテ削除ボタンを押したとき"]
N0194["1. 削除確認ダイアログを表示する。"]
N0195["2. 「はい」を押したとき段落3-1に移動する。「いいえ」を押したとき段落4-1に移動する。。"]
N0196["2. 「はい」を押したとき段落3-1に移動する。"]
N0197["2. 「いいえ」を押したとき段落4-1に移動する。"]
N0198["3-1. ローディング画面を表示する。"]
N0199["3-2. ローディング画面を閉じる。"]
N0200["3-3. 削除完了のメッセージが表示される。"]
N0201["3-4. 「OK」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
N0202["4-1. 削除確認ダイアログを閉じる。"]
N0203["4-2. シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_25["カルテ復活ボタンを押したとき"]
N0204["1. 復活確認ダイアログを表示する。"]
N0205["2. 「はい」を押したとき段落3-1に移動する。「いいえ」を押したとき段落4-1に移動する。。"]
N0206["2. 「はい」を押したとき段落3-1に移動する。"]
N0207["2. 「いいえ」を押したとき段落4-1に移動する。"]
N0208["3-1. ローディング画面を表示する。"]
N0209["3-2. ローディング画面を閉じる。"]
N0210["3-3. 復活完了のメッセージが表示される。"]
N0211["3-4. 「OK」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
N0212["4-1. 復活確認ダイアログを閉じる。"]
N0213["4-2. シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_26["保険請求書類を選択ボタンを押したとき"]
N0214["1. 保険請求書類選択画面に移動する。"]
N0215["2. 選択対象のカルテ情報が表示される。"]
N0216["3. 保険会社、書類名、書類バージョンの検索欄と検索ボタンが表示される。"]
N0217["4. 書類一覧テーブルに会社名、書類名、バージョン、更新日が表示される。並び替え機能、検索結果のうち30件のみ表示、続きを表示ボタンが表示される。"]
N0218["5. 「ダウンロード」ボタンを押したとき、シーン「書類ダウンロードボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。。"]
N0219["5. 「ダウンロード」ボタンを押したとき、シーン「書類ダウンロードボタンを押したとき」に移動する。"]
N0220["5. 「戻る」ボタンを押したとき、シーン「カルテ検索アイコンを押したとき」の4-1.〜4-4.と同様。"]
TITLE_27["書類ダウンロードボタンを押したとき"]
N0221["1. 印刷前注意ダイアログを表示し、「Chrome推奨、それ以外は印刷位置がずれる可能性がある」旨を表示する。"]
N0222["2. 「OK」を押したとき段落3-1に移動する。「戻る」を押したとき段落4-1に移動する。。"]
N0223["2. 「OK」を押したとき段落3-1に移動する。"]
N0224["2. 「戻る」を押したとき段落4-1に移動する。"]
N0225["3-1. 書類プレビュー画面に移動する。"]
N0226["3-2. 画面上に印刷対象の書類が表示される。"]
N0227["3-3. 「印刷」ボタンを押したとき、シーン「印刷ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「保険請求書類を選択ボタンを押したとき」の1.〜5.と同様。。"]
N0228["3-3. 「印刷」ボタンを押したとき、シーン「印刷ボタンを押したとき」に移動する。"]
N0229["3-3. 「戻る」ボタンを押したとき、シーン「保険請求書類を選択ボタンを押したとき」の1.〜5.と同様。"]
N0230["4-1. 印刷前注意ダイアログを閉じる。"]
N0231["4-2. シーン「保険請求書類を選択ボタンを押したとき」の1.〜5.と同様。"]
TITLE_28["印刷ボタンを押したとき"]
N0232["1. ブラウザの印刷ダイアログが表示される。"]
N0233["2. 「印刷」または「PDFとして保存」を実行したとき、このシーンの段落3-1に移動する。「キャンセル」を押したとき段落4-1に移動する。。"]
N0234["2. 「印刷」または「PDFとして保存」を実行したとき、このシーンの段落3-1に移動する。"]
N0235["2. 「キャンセル」を押したとき段落4-1に移動する。"]
N0236["3-1. ブラウザの印刷ダイアログを閉じる。"]
N0237["3-2. シーン「書類ダウンロードボタンを押したとき」の3-1.〜3-3.と同様。"]
N0238["4-1. ブラウザの印刷ダイアログを閉じる。"]
N0239["4-2. シーン「書類ダウンロードボタンを押したとき」の3-1.〜3-3.と同様。"]
TITLE_29["患者マスタアイコンを押したとき"]
N0240["1. 患者マスタ画面に移動する。"]
N0241["2. 検索欄に患者ID、氏名、生年月日、電話番号、削除済み表示切替が表示される。"]
N0242["3. 「検索」ボタンを押したとき、段落4-1に移動する。「新規登録」ボタンを押したとき、シーン「患者マスタ新規登録ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0243["3. 「検索」ボタンを押したとき、段落4-1に移動する。"]
N0244["3. 「新規登録」ボタンを押したとき、シーン「患者マスタ新規登録ボタンを押したとき」に移動する。"]
N0245["3. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
N0246["4-1. 検索結果テーブルに患者ID、氏名、生年月日、性別、電話番号、削除状態が表示される。"]
N0247["4-2. 並び替え機能、検索結果のうち30件のみ表示、続きを表示ボタンが表示される。"]
N0248["4-3. 各行に「詳細」「編集」「削除」「復活」ボタンが表示される。ユーザー権限が閲覧者の場合「編集」「削除」「復活」ボタンは非表示となり、押下不能である。ユーザー権限が入力者の場合「削除」「復活」ボタンは非表示となり、押下不能である。削除済みの行にのみ「復活」ボタンが表示される。"]
N0249["4-4. 「詳細」ボタンを押したとき、シーン「患者マスタ詳細ボタンを押したとき」に移動する。「編集」ボタンを押したとき、シーン「患者マスタ編集ボタンを押したとき」に移動する。「削除」ボタンを押したとき、シーン「患者マスタ削除ボタンを押したとき」に移動する。「復活」ボタンを押したとき、シーン「患者マスタ復活ボタンを押したとき」に移動する。。"]
N0250["4-4. 「詳細」ボタンを押したとき、シーン「患者マスタ詳細ボタンを押したとき」に移動する。"]
N0251["4-4. 「編集」ボタンを押したとき、シーン「患者マスタ編集ボタンを押したとき」に移動する。"]
N0252["4-4. 「削除」ボタンを押したとき、シーン「患者マスタ削除ボタンを押したとき」に移動する。"]
N0253["4-4. 「復活」ボタンを押したとき、シーン「患者マスタ復活ボタンを押したとき」に移動する。"]
TITLE_30["患者マスタ新規登録ボタンを押したとき"]
N0254["1. 患者マスタ新規登録画面に移動する。"]
N0255["2. 患者ID、生年月日、苗字、名前、性別、住所、電話番号などの入力欄が表示される。"]
N0256["3. 「登録する」ボタンを押したとき、シーン「患者マスタ登録ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。。"]
N0257["3. 「登録する」ボタンを押したとき、シーン「患者マスタ登録ボタンを押したとき」に移動する。"]
N0258["3. 「戻る」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_31["患者マスタ登録ボタンを押したとき"]
N0259["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。患者IDが同グループ内で重複している場合は段落3-1に移動する。生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。入力内容に問題がない場合は段落5-1に移動する。。"]
N0260["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0261["1. 患者IDが同グループ内で重複している場合は段落3-1に移動する。"]
N0262["1. 生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。"]
N0263["1. 入力内容に問題がない場合は段落5-1に移動する。"]
N0264["2-1. 入力エラーを表示する。"]
N0265["2-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「患者マスタ新規登録ボタンを押したとき」に移動する。。"]
N0266["2-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。"]
N0267["2-2. 「戻る」ボタンを押したとき、シーン「患者マスタ新規登録ボタンを押したとき」に移動する。"]
N0268["3-1. 患者IDが重複している旨のエラーが表示される。"]
N0269["3-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「患者マスタ新規登録ボタンを押したとき」に移動する。。"]
N0270["3-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。"]
N0271["3-2. 「戻る」ボタンを押したとき、シーン「患者マスタ新規登録ボタンを押したとき」に移動する。"]
N0272["4-1. 類似患者が存在する旨の警告ダイアログを表示する。"]
N0273["4-2. ダイアログ内に類似候補の患者ID・氏名・生年月日が一覧表示される。"]
N0274["4-3. 「このまま登録する」を押したとき段落5-1に移動する。「戻る」を押したとき段落6-1に移動する。。"]
N0275["4-3. 「このまま登録する」を押したとき段落5-1に移動する。"]
N0276["4-3. 「戻る」を押したとき段落6-1に移動する。"]
N0277["5-1. 登録確認ダイアログを表示する。"]
N0278["5-2. 「はい」を押したとき段落7-1に移動する。「いいえ」を押したとき段落6-1に移動する。。"]
N0279["5-2. 「はい」を押したとき段落7-1に移動する。"]
N0280["5-2. 「いいえ」を押したとき段落6-1に移動する。"]
N0281["6-1. ダイアログを閉じる。"]
N0282["6-2. シーン「患者マスタ新規登録ボタンを押したとき」の1.〜3.と同様。"]
N0283["7-1. ローディング画面を表示する。"]
N0284["7-2. ローディング画面を閉じる。"]
N0285["7-3. 登録完了のメッセージが表示される。"]
N0286["7-4. 「OK」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_32["患者マスタ詳細ボタンを押したとき"]
N0287["1. 患者マスタ詳細画面に移動する。"]
N0288["2. 患者マスタの内容が表示される。"]
N0289["3. 「戻る」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_33["患者マスタ編集ボタンを押したとき"]
N0290["1. 患者マスタ編集画面に移動する。"]
N0291["2. 既存の患者情報が入力欄に表示される。"]
N0292["3. 「更新する」ボタンを押したとき、シーン「患者マスタ更新ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。。"]
N0293["3. 「更新する」ボタンを押したとき、シーン「患者マスタ更新ボタンを押したとき」に移動する。"]
N0294["3. 「戻る」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_34["患者マスタ更新ボタンを押したとき"]
N0295["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。患者IDが同グループ内で重複している場合は段落3-1に移動する。生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。入力内容に問題がない場合は段落5-1に移動する。。"]
N0296["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0297["1. 患者IDが同グループ内で重複している場合は段落3-1に移動する。"]
N0298["1. 生年月日が完全一致かつ氏名の2文字以上が部分一致する既存患者がいる場合は段落4-1に移動する。"]
N0299["1. 入力内容に問題がない場合は段落5-1に移動する。"]
N0300["2-1. 入力エラーを表示する。"]
N0301["2-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「患者マスタ編集ボタンを押したとき」に移動する。。"]
N0302["2-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。"]
N0303["2-2. 「戻る」ボタンを押したとき、シーン「患者マスタ編集ボタンを押したとき」に移動する。"]
N0304["3-1. 患者IDが重複している旨のエラーが表示される。"]
N0305["3-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「患者マスタ編集ボタンを押したとき」に移動する。。"]
N0306["3-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。"]
N0307["3-2. 「戻る」ボタンを押したとき、シーン「患者マスタ編集ボタンを押したとき」に移動する。"]
N0308["4-1. 類似患者が存在する旨の警告ダイアログを表示する。"]
N0309["4-2. ダイアログ内に類似候補の患者ID・氏名・生年月日が一覧表示される。"]
N0310["4-3. 「このまま更新する」を押したとき段落5-1に移動する。「戻る」を押したとき段落6-1に移動する。。"]
N0311["4-3. 「このまま更新する」を押したとき段落5-1に移動する。"]
N0312["4-3. 「戻る」を押したとき段落6-1に移動する。"]
N0313["5-1. 更新確認ダイアログを表示する。"]
N0314["5-2. 「はい」を押したとき段落7-1に移動する。「いいえ」を押したとき段落6-1に移動する。。"]
N0315["5-2. 「はい」を押したとき段落7-1に移動する。"]
N0316["5-2. 「いいえ」を押したとき段落6-1に移動する。"]
N0317["6-1. ダイアログを閉じる。"]
N0318["6-2. シーン「患者マスタ編集ボタンを押したとき」の1.〜3.と同様。"]
N0319["7-1. ローディング画面を表示する。"]
N0320["7-2. ローディング画面を閉じる。"]
N0321["7-3. 更新完了のメッセージが表示される。"]
N0322["7-4. 「OK」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_35["患者マスタ削除ボタンを押したとき"]
N0323["1. 削除確認ダイアログを表示する。"]
N0324["2. 「はい」を押したとき段落3-1に移動する。「いいえ」を押したとき段落4-1に移動する。。"]
N0325["2. 「はい」を押したとき段落3-1に移動する。"]
N0326["2. 「いいえ」を押したとき段落4-1に移動する。"]
N0327["3-1. ローディング画面を表示する。"]
N0328["3-2. ローディング画面を閉じる。"]
N0329["3-3. 削除完了のメッセージが表示される。"]
N0330["3-4. 「OK」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
N0331["4-1. 削除確認ダイアログを閉じる。"]
N0332["4-2. シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_36["患者マスタ復活ボタンを押したとき"]
N0333["1. 復活確認ダイアログを表示する。"]
N0334["2. 「はい」を押したとき段落3-1に移動する。「いいえ」を押したとき段落4-1に移動する。。"]
N0335["2. 「はい」を押したとき段落3-1に移動する。"]
N0336["2. 「いいえ」を押したとき段落4-1に移動する。"]
N0337["3-1. ローディング画面を表示する。"]
N0338["3-2. ローディング画面を閉じる。"]
N0339["3-3. 復活完了のメッセージが表示される。"]
N0340["3-4. 「OK」ボタンを押したとき、シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
N0341["4-1. 復活確認ダイアログを閉じる。"]
N0342["4-2. シーン「患者マスタアイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_37["アカウント管理アイコンを押したとき"]
N0343["1. アカウント管理画面に移動する。"]
N0344["2. 検索欄にログインID、氏名、権限、削除済み表示切替が表示される。"]
N0345["3. 「検索」ボタンを押したとき、段落4-1に移動する。「新規作成」ボタンを押したとき、シーン「アカウント新規作成ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0346["3. 「検索」ボタンを押したとき、段落4-1に移動する。"]
N0347["3. 「新規作成」ボタンを押したとき、シーン「アカウント新規作成ボタンを押したとき」に移動する。"]
N0348["3. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
N0349["4-1. 検索結果テーブルにログインID、氏名、権限、作成日、削除状態が表示される。"]
N0350["4-2. 並び替え機能、検索結果のうち30件のみ表示、続きを表示ボタンが表示される。"]
N0351["4-3. 各行に「詳細」「編集」「削除」「復活」ボタンが表示される。ユーザー権限が管理者でない場合、アカウント管理画面自体が表示されない。削除済みの行にのみ「復活」ボタンが表示される。"]
N0352["4-4. 「詳細」ボタンを押したとき、シーン「アカウント詳細ボタンを押したとき」に移動する。「編集」ボタンを押したとき、シーン「アカウント編集ボタンを押したとき」に移動する。「削除」ボタンを押したとき、シーン「アカウント削除ボタンを押したとき」に移動する。「復活」ボタンを押したとき、シーン「アカウント復活ボタンを押したとき」に移動する。。"]
N0353["4-4. 「詳細」ボタンを押したとき、シーン「アカウント詳細ボタンを押したとき」に移動する。"]
N0354["4-4. 「編集」ボタンを押したとき、シーン「アカウント編集ボタンを押したとき」に移動する。"]
N0355["4-4. 「削除」ボタンを押したとき、シーン「アカウント削除ボタンを押したとき」に移動する。"]
N0356["4-4. 「復活」ボタンを押したとき、シーン「アカウント復活ボタンを押したとき」に移動する。"]
TITLE_38["アカウント新規作成ボタンを押したとき"]
N0357["1. アカウント新規作成画面に移動する。"]
N0358["2. 氏名、パスワード、権限（管理者・入力者・閲覧者）を入力する欄が表示され、ログインIDは自動採番として表示される。"]
N0359["3. 「登録する」ボタンを押したとき、シーン「アカウント登録ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。。"]
N0360["3. 「登録する」ボタンを押したとき、シーン「アカウント登録ボタンを押したとき」に移動する。"]
N0361["3. 「戻る」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_39["アカウント登録ボタンを押したとき"]
N0362["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。入力内容に問題がない場合は段落3-1に移動する。。"]
N0363["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0364["1. 入力内容に問題がない場合は段落3-1に移動する。"]
N0365["2-1. 入力エラーを表示する。"]
N0366["2-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「アカウント新規作成ボタンを押したとき」に移動する。。"]
N0367["2-2. 入力内容を修正し「登録する」ボタンを押したとき、このシーンの最初に移動する。"]
N0368["2-2. 「戻る」ボタンを押したとき、シーン「アカウント新規作成ボタンを押したとき」に移動する。"]
N0369["3-1. 登録確認ダイアログを表示する。"]
N0370["3-2. 「はい」を押したとき段落4-1に移動する。「いいえ」を押したとき段落5-1に移動する。。"]
N0371["3-2. 「はい」を押したとき段落4-1に移動する。"]
N0372["3-2. 「いいえ」を押したとき段落5-1に移動する。"]
N0373["4-1. ローディング画面を表示する。"]
N0374["4-2. ローディング画面を閉じる。"]
N0375["4-3. 登録完了のメッセージが表示される。"]
N0376["4-4. 「OK」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
N0377["5-1. 登録確認ダイアログを閉じる。"]
N0378["5-2. シーン「アカウント新規作成ボタンを押したとき」の1.〜3.と同様。"]
TITLE_40["アカウント詳細ボタンを押したとき"]
N0379["1. アカウント詳細画面に移動する。"]
N0380["2. 氏名、ログインID、権限、作成日、削除状態が表示される。"]
N0381["3. 「戻る」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_41["アカウント編集ボタンを押したとき"]
N0382["1. アカウント編集画面に移動する。"]
N0383["2. 氏名、パスワード、権限の入力欄が表示される。"]
N0384["3. 「更新する」ボタンを押したとき、シーン「アカウント更新ボタンを押したとき」に移動する。「戻る」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。。"]
N0385["3. 「更新する」ボタンを押したとき、シーン「アカウント更新ボタンを押したとき」に移動する。"]
N0386["3. 「戻る」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_42["アカウント更新ボタンを押したとき"]
N0387["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。入力内容に問題がない場合は段落3-1に移動する。。"]
N0388["1. 入力内容に未入力や形式エラーがある場合は段落2-1に移動する。"]
N0389["1. 入力内容に問題がない場合は段落3-1に移動する。"]
N0390["2-1. 入力エラーを表示する。"]
N0391["2-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。「戻る」ボタンを押したとき、シーン「アカウント編集ボタンを押したとき」に移動する。。"]
N0392["2-2. 入力内容を修正し「更新する」ボタンを押したとき、このシーンの最初に移動する。"]
N0393["2-2. 「戻る」ボタンを押したとき、シーン「アカウント編集ボタンを押したとき」に移動する。"]
N0394["3-1. 更新確認ダイアログを表示する。"]
N0395["3-2. 「はい」を押したとき段落4-1に移動する。「いいえ」を押したとき段落5-1に移動する。。"]
N0396["3-2. 「はい」を押したとき段落4-1に移動する。"]
N0397["3-2. 「いいえ」を押したとき段落5-1に移動する。"]
N0398["4-1. ローディング画面を表示する。"]
N0399["4-2. ローディング画面を閉じる。"]
N0400["4-3. 更新完了のメッセージが表示される。"]
N0401["4-4. 「OK」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
N0402["5-1. 更新確認ダイアログを閉じる。"]
N0403["5-2. シーン「アカウント編集ボタンを押したとき」の1.〜3.と同様。"]
TITLE_43["アカウント削除ボタンを押したとき"]
N0404["1. 削除確認ダイアログを表示する。"]
N0405["2. 「はい」を押したとき段落3-1に移動する。「いいえ」を押したとき段落4-1に移動する。。"]
N0406["2. 「はい」を押したとき段落3-1に移動する。"]
N0407["2. 「いいえ」を押したとき段落4-1に移動する。"]
N0408["3-1. ローディング画面を表示する。"]
N0409["3-2. ローディング画面を閉じる。"]
N0410["3-3. 削除完了のメッセージが表示される。"]
N0411["3-4. 「OK」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
N0412["4-1. 削除確認ダイアログを閉じる。"]
N0413["4-2. シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_44["アカウント復活ボタンを押したとき"]
N0414["1. 復活確認ダイアログを表示する。"]
N0415["2. 「はい」を押したとき段落3-1に移動する。「いいえ」を押したとき段落4-1に移動する。。"]
N0416["2. 「はい」を押したとき段落3-1に移動する。"]
N0417["2. 「いいえ」を押したとき段落4-1に移動する。"]
N0418["3-1. ローディング画面を表示する。"]
N0419["3-2. ローディング画面を閉じる。"]
N0420["3-3. 復活完了のメッセージが表示される。"]
N0421["3-4. 「OK」ボタンを押したとき、シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
N0422["4-1. 復活確認ダイアログを閉じる。"]
N0423["4-2. シーン「アカウント管理アイコンを押したとき」の2.〜4-4.と同様。"]
TITLE_45["使用履歴ボタンを押したとき"]
N0424["1. 使用履歴画面に移動する。"]
N0425["2. 検索欄に操作種別、対象種別、実行者、期間、削除済み表示切替が表示される。"]
N0426["3. 「検索」ボタンを押したとき、段落4-1に移動する。「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。。"]
N0427["3. 「検索」ボタンを押したとき、段落4-1に移動する。"]
N0428["3. 「戻る」ボタンを押したとき、シーン「ホーム画面に戻るボタンを押したとき」に移動する。"]
N0429["4-1. 使用履歴テーブルに操作日時、実行者、操作種別、対象種別、対象IDが表示される。"]
N0430["4-2. 並び替え機能、検索結果のうち30件のみ表示、続きを表示ボタンが表示される。"]
N0431["4-3. 「詳細」ボタンを押したとき、シーン「使用履歴詳細ボタンを押したとき」に移動する。"]
TITLE_46["使用履歴詳細ボタンを押したとき"]
N0432["1. 使用履歴詳細画面に移動する。"]
N0433["2. 操作日時、実行者、操作内容、対象情報の詳細が表示される。"]
N0434["3. 「戻る」ボタンを押したとき、シーン「使用履歴ボタンを押したとき」の2.〜4-3.と同様。"]
START_システムを開いたとき["システムを開いたとき：開始"]
START_ログインボタンを押したとき["ログインボタンを押したとき：開始"]
START_ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき）["ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき）：開始"]
START_ホーム画面の各アイコンを押したとき（呼び出し元：ログインボタンを押したとき）["ホーム画面の各アイコンを押したとき（呼び出し元：ログインボタンを押したとき）：開始"]
START_ハンバーガーメニューを押したとき["ハンバーガーメニューを押したとき：開始"]
START_利用規約ボタンを押したとき（呼び出し元：ログイン画面）["利用規約ボタンを押したとき（呼び出し元：ログイン画面）：開始"]
START_ログイン画面に戻るボタンを押したとき["ログイン画面に戻るボタンを押したとき：開始"]
START_利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー）["利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー）：開始"]
START_ハンバーガーメニューに戻るボタンを押したとき["ハンバーガーメニューに戻るボタンを押したとき：開始"]
START_ログアウトボタンを押したとき["ログアウトボタンを押したとき：開始"]
START_ログイン情報変更ボタンを押したとき["ログイン情報変更ボタンを押したとき：開始"]
START_ホーム画面に戻るボタンを押したとき["ホーム画面に戻るボタンを押したとき：開始"]
START_ログイン情報変更の変更するボタンを押したとき["ログイン情報変更の変更するボタンを押したとき：開始"]
START_カルテ新規入力アイコンを押したとき["カルテ新規入力アイコンを押したとき：開始"]
START_カルテ新規入力：既存患者タブを押したとき["カルテ新規入力：既存患者タブを押したとき：開始"]
START_カルテ新規入力：新規患者タブを押したとき["カルテ新規入力：新規患者タブを押したとき：開始"]
START_カルテ登録ボタンを押したとき["カルテ登録ボタンを押したとき：開始"]
START_カルテ検索アイコンを押したとき["カルテ検索アイコンを押したとき：開始"]
START_カルテ詳細ボタンを押したとき["カルテ詳細ボタンを押したとき：開始"]
START_カルテ編集ボタンを押したとき["カルテ編集ボタンを押したとき：開始"]
START_カルテ編集：既存患者タブを押したとき["カルテ編集：既存患者タブを押したとき：開始"]
START_カルテ編集：新規患者タブを押したとき["カルテ編集：新規患者タブを押したとき：開始"]
START_カルテ更新ボタンを押したとき["カルテ更新ボタンを押したとき：開始"]
START_カルテ削除ボタンを押したとき["カルテ削除ボタンを押したとき：開始"]
START_カルテ復活ボタンを押したとき["カルテ復活ボタンを押したとき：開始"]
START_保険請求書類を選択ボタンを押したとき["保険請求書類を選択ボタンを押したとき：開始"]
START_書類ダウンロードボタンを押したとき["書類ダウンロードボタンを押したとき：開始"]
START_印刷ボタンを押したとき["印刷ボタンを押したとき：開始"]
START_患者マスタアイコンを押したとき["患者マスタアイコンを押したとき：開始"]
START_患者マスタ新規登録ボタンを押したとき["患者マスタ新規登録ボタンを押したとき：開始"]
START_患者マスタ登録ボタンを押したとき["患者マスタ登録ボタンを押したとき：開始"]
START_患者マスタ詳細ボタンを押したとき["患者マスタ詳細ボタンを押したとき：開始"]
START_患者マスタ編集ボタンを押したとき["患者マスタ編集ボタンを押したとき：開始"]
START_患者マスタ更新ボタンを押したとき["患者マスタ更新ボタンを押したとき：開始"]
START_患者マスタ削除ボタンを押したとき["患者マスタ削除ボタンを押したとき：開始"]
START_患者マスタ復活ボタンを押したとき["患者マスタ復活ボタンを押したとき：開始"]
START_アカウント管理アイコンを押したとき["アカウント管理アイコンを押したとき：開始"]
START_アカウント新規作成ボタンを押したとき["アカウント新規作成ボタンを押したとき：開始"]
START_アカウント登録ボタンを押したとき["アカウント登録ボタンを押したとき：開始"]
START_アカウント詳細ボタンを押したとき["アカウント詳細ボタンを押したとき：開始"]
START_アカウント編集ボタンを押したとき["アカウント編集ボタンを押したとき：開始"]
START_アカウント更新ボタンを押したとき["アカウント更新ボタンを押したとき：開始"]
START_アカウント削除ボタンを押したとき["アカウント削除ボタンを押したとき：開始"]
START_アカウント復活ボタンを押したとき["アカウント復活ボタンを押したとき：開始"]
START_使用履歴ボタンを押したとき["使用履歴ボタンを押したとき：開始"]
START_使用履歴詳細ボタンを押したとき["使用履歴詳細ボタンを押したとき：開始"]
N0001 --> N0002
N0001 --> N0003
N0001 --> N0004
N0004 --> N0005
N0005 --> N0006
N0006 --> N0007
N0008 --> N0009
N0009 --> N0010
N0010 --> N0011
N0011 --> START_ログインボタンを押したとき
N0010 --> N0012
N0012 --> START_利用規約ボタンを押したとき（呼び出し元：ログイン画面）
N0013 --> N0014
N0013 --> N0015
N0013 --> N0016
N0016 --> N0017
N0017 --> N0018
N0017 --> N0019
N0019 --> START_利用規約ボタンを押したとき（呼び出し元：ログイン画面）
N0017 --> N0020
N0020 --> N0021
N0021 --> N0022
N0022 --> N0023
N0024 --> N0025
N0025 --> N0026
N0026 --> N0027
N0027 --> START_ハンバーガーメニューを押したとき
N0026 --> N0028
N0026 --> N0029
N0029 --> START_カルテ新規入力アイコンを押したとき
N0030 --> START_カルテ検索アイコンを押したとき
N0031 --> START_患者マスタアイコンを押したとき
N0032 --> START_アカウント管理アイコンを押したとき
N0034 --> N0035
N0035 --> N0036
N0036 --> START_カルテ新規入力アイコンを押したとき
N0037 --> START_カルテ検索アイコンを押したとき
N0038 --> START_患者マスタアイコンを押したとき
N0039 --> START_アカウント管理アイコンを押したとき
N0040 --> START_ログイン情報変更ボタンを押したとき
N0041 --> START_使用履歴ボタンを押したとき
N0042 --> START_利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー）
N0043 --> START_ログアウトボタンを押したとき
N0044 --> N0045
N0045 --> N0046
N0046 --> START_ログイン画面に戻るボタンを押したとき
N0047 --> N0048
N0048 --> N0049
N0049 --> N0050
N0049 --> N0051
N0052 --> N0053
N0053 --> N0054
N0054 --> START_ハンバーガーメニューに戻るボタンを押したとき
N0055 --> N0056
N0057 --> N0058
N0058 --> N0059
N0058 --> N0060
N0058 --> N0061
N0061 --> N0062
N0062 --> N0063
N0063 --> N0064
N0065 --> N0066
N0067 --> N0068
N0068 --> N0069
N0069 --> N0070
N0070 --> START_ログイン情報変更の変更するボタンを押したとき
N0069 --> N0071
N0071 --> START_ホーム画面に戻るボタンを押したとき
N0072 --> N0073
N0074 --> N0075
N0074 --> N0076
N0074 --> N0077
N0077 --> N0078
N0078 --> N0079
N0078 --> N0080
N0078 --> N0081
N0081 --> N0082
N0082 --> N0083
N0082 --> N0084
N0082 --> N0085
N0085 --> N0086
N0086 --> N0087
N0087 --> N0088
N0089 --> N0090
N0091 --> N0092
N0092 --> N0093
N0093 --> N0094
N0094 --> START_カルテ新規入力：既存患者タブを押したとき
N0093 --> N0095
N0095 --> START_カルテ新規入力：新規患者タブを押したとき
N0096 --> N0097
N0097 --> N0098
N0098 --> N0099
N0099 --> N0100
N0100 --> N0101
N0101 --> START_カルテ登録ボタンを押したとき
N0100 --> N0102
N0103 --> N0104
N0104 --> N0105
N0105 --> N0106
N0106 --> START_カルテ登録ボタンを押したとき
N0105 --> N0107
N0108 --> N0109
N0108 --> N0110
N0108 --> N0111
N0108 --> N0112
N0108 --> N0113
N0113 --> N0114
N0114 --> N0115
N0114 --> N0116
N0114 --> N0117
N0117 --> N0118
N0118 --> N0119
N0118 --> N0120
N0118 --> N0121
N0121 --> N0122
N0122 --> N0123
N0123 --> N0124
N0123 --> N0125
N0123 --> N0126
N0126 --> N0127
N0127 --> N0128
N0127 --> N0129
N0127 --> N0130
N0130 --> N0131
N0132 --> N0133
N0133 --> N0134
N0134 --> N0135
N0136 --> N0137
N0137 --> N0138
N0138 --> N0139
N0138 --> N0140
N0138 --> N0141
N0141 --> N0142
N0142 --> N0143
N0143 --> N0144
N0144 --> N0145
N0145 --> START_カルテ詳細ボタンを押したとき
N0144 --> N0146
N0146 --> START_カルテ編集ボタンを押したとき
N0144 --> N0147
N0147 --> START_カルテ削除ボタンを押したとき
N0144 --> N0148
N0148 --> START_カルテ復活ボタンを押したとき
N0144 --> N0149
N0149 --> START_保険請求書類を選択ボタンを押したとき
N0150 --> N0151
N0151 --> N0152
N0153 --> N0154
N0154 --> N0155
N0155 --> N0156
N0156 --> START_カルテ編集：既存患者タブを押したとき
N0155 --> N0157
N0157 --> START_カルテ編集：新規患者タブを押したとき
N0159 --> N0160
N0160 --> START_カルテ更新ボタンを押したとき
N0159 --> N0161
N0163 --> N0164
N0164 --> START_カルテ更新ボタンを押したとき
N0163 --> N0165
N0166 --> N0167
N0166 --> N0168
N0166 --> N0169
N0166 --> N0170
N0166 --> N0171
N0171 --> N0172
N0172 --> N0173
N0172 --> N0174
N0172 --> N0175
N0175 --> N0176
N0176 --> N0177
N0176 --> N0178
N0176 --> N0179
N0179 --> N0180
N0180 --> N0181
N0181 --> N0182
N0181 --> N0183
N0181 --> N0184
N0184 --> N0185
N0185 --> N0186
N0185 --> N0187
N0185 --> N0188
N0188 --> N0189
N0190 --> N0191
N0191 --> N0192
N0192 --> N0193
N0194 --> N0195
N0195 --> N0196
N0195 --> N0197
N0195 --> N0198
N0198 --> N0199
N0199 --> N0200
N0200 --> N0201
N0202 --> N0203
N0204 --> N0205
N0205 --> N0206
N0205 --> N0207
N0205 --> N0208
N0208 --> N0209
N0209 --> N0210
N0210 --> N0211
N0212 --> N0213
N0214 --> N0215
N0215 --> N0216
N0216 --> N0217
N0217 --> N0218
N0218 --> N0219
N0219 --> START_書類ダウンロードボタンを押したとき
N0218 --> N0220
N0221 --> N0222
N0222 --> N0223
N0222 --> N0224
N0222 --> N0225
N0225 --> N0226
N0226 --> N0227
N0227 --> N0228
N0228 --> START_印刷ボタンを押したとき
N0227 --> N0229
N0227 --> N0230
N0230 --> N0231
N0232 --> N0233
N0233 --> N0234
N0233 --> N0235
N0233 --> N0236
N0236 --> N0237
N0238 --> N0239
N0240 --> N0241
N0241 --> N0242
N0242 --> N0243
N0242 --> N0244
N0244 --> START_患者マスタ新規登録ボタンを押したとき
N0242 --> N0245
N0242 --> N0246
N0246 --> N0247
N0247 --> N0248
N0248 --> N0249
N0249 --> N0250
N0250 --> START_患者マスタ詳細ボタンを押したとき
N0249 --> N0251
N0251 --> START_患者マスタ編集ボタンを押したとき
N0249 --> N0252
N0252 --> START_患者マスタ削除ボタンを押したとき
N0249 --> N0253
N0253 --> START_患者マスタ復活ボタンを押したとき
N0254 --> N0255
N0255 --> N0256
N0256 --> N0257
N0257 --> START_患者マスタ登録ボタンを押したとき
N0256 --> N0258
N0259 --> N0260
N0259 --> N0261
N0259 --> N0262
N0259 --> N0263
N0259 --> N0264
N0264 --> N0265
N0265 --> N0266
N0265 --> N0267
N0265 --> N0268
N0268 --> N0269
N0269 --> N0270
N0269 --> N0271
N0269 --> N0272
N0272 --> N0273
N0273 --> N0274
N0274 --> N0275
N0274 --> N0276
N0274 --> N0277
N0277 --> N0278
N0278 --> N0279
N0278 --> N0280
N0278 --> N0281
N0281 --> N0282
N0283 --> N0284
N0284 --> N0285
N0285 --> N0286
N0287 --> N0288
N0288 --> N0289
N0290 --> N0291
N0291 --> N0292
N0292 --> N0293
N0293 --> START_患者マスタ更新ボタンを押したとき
N0292 --> N0294
N0295 --> N0296
N0295 --> N0297
N0295 --> N0298
N0295 --> N0299
N0295 --> N0300
N0300 --> N0301
N0301 --> N0302
N0301 --> N0303
N0301 --> N0304
N0304 --> N0305
N0305 --> N0306
N0305 --> N0307
N0305 --> N0308
N0308 --> N0309
N0309 --> N0310
N0310 --> N0311
N0310 --> N0312
N0310 --> N0313
N0313 --> N0314
N0314 --> N0315
N0314 --> N0316
N0314 --> N0317
N0317 --> N0318
N0319 --> N0320
N0320 --> N0321
N0321 --> N0322
N0323 --> N0324
N0324 --> N0325
N0324 --> N0326
N0324 --> N0327
N0327 --> N0328
N0328 --> N0329
N0329 --> N0330
N0331 --> N0332
N0333 --> N0334
N0334 --> N0335
N0334 --> N0336
N0334 --> N0337
N0337 --> N0338
N0338 --> N0339
N0339 --> N0340
N0341 --> N0342
N0343 --> N0344
N0344 --> N0345
N0345 --> N0346
N0345 --> N0347
N0347 --> START_アカウント新規作成ボタンを押したとき
N0345 --> N0348
N0345 --> N0349
N0349 --> N0350
N0350 --> N0351
N0351 --> N0352
N0352 --> N0353
N0353 --> START_アカウント詳細ボタンを押したとき
N0352 --> N0354
N0354 --> START_アカウント編集ボタンを押したとき
N0352 --> N0355
N0355 --> START_アカウント削除ボタンを押したとき
N0352 --> N0356
N0356 --> START_アカウント復活ボタンを押したとき
N0357 --> N0358
N0358 --> N0359
N0359 --> N0360
N0360 --> START_アカウント登録ボタンを押したとき
N0359 --> N0361
N0362 --> N0363
N0362 --> N0364
N0362 --> N0365
N0365 --> N0366
N0366 --> N0367
N0366 --> N0368
N0366 --> N0369
N0369 --> N0370
N0370 --> N0371
N0370 --> N0372
N0370 --> N0373
N0373 --> N0374
N0374 --> N0375
N0375 --> N0376
N0377 --> N0378
N0379 --> N0380
N0380 --> N0381
N0382 --> N0383
N0383 --> N0384
N0384 --> N0385
N0385 --> START_アカウント更新ボタンを押したとき
N0384 --> N0386
N0387 --> N0388
N0387 --> N0389
N0387 --> N0390
N0390 --> N0391
N0391 --> N0392
N0391 --> N0393
N0391 --> N0394
N0394 --> N0395
N0395 --> N0396
N0395 --> N0397
N0395 --> N0398
N0398 --> N0399
N0399 --> N0400
N0400 --> N0401
N0402 --> N0403
N0404 --> N0405
N0405 --> N0406
N0405 --> N0407
N0405 --> N0408
N0408 --> N0409
N0409 --> N0410
N0410 --> N0411
N0412 --> N0413
N0414 --> N0415
N0415 --> N0416
N0415 --> N0417
N0415 --> N0418
N0418 --> N0419
N0419 --> N0420
N0420 --> N0421
N0422 --> N0423
N0424 --> N0425
N0425 --> N0426
N0426 --> N0427
N0426 --> N0428
N0426 --> N0429
N0429 --> N0430
N0430 --> N0431
N0431 --> START_使用履歴詳細ボタンを押したとき
N0432 --> N0433
N0433 --> N0434
START_システムを開いたとき --> N0001
START_ログインボタンを押したとき --> N0013
START_ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき） --> N0024
START_ホーム画面の各アイコンを押したとき（呼び出し元：ログインボタンを押したとき） --> N0033
START_ハンバーガーメニューを押したとき --> N0034
START_利用規約ボタンを押したとき（呼び出し元：ログイン画面） --> N0044
START_ログイン画面に戻るボタンを押したとき --> N0047
START_利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー） --> N0052
START_ハンバーガーメニューに戻るボタンを押したとき --> N0055
START_ログアウトボタンを押したとき --> N0057
START_ログイン情報変更ボタンを押したとき --> N0067
START_ホーム画面に戻るボタンを押したとき --> N0072
START_ログイン情報変更の変更するボタンを押したとき --> N0074
START_カルテ新規入力アイコンを押したとき --> N0091
START_カルテ新規入力：既存患者タブを押したとき --> N0096
START_カルテ新規入力：新規患者タブを押したとき --> N0103
START_カルテ登録ボタンを押したとき --> N0108
START_カルテ検索アイコンを押したとき --> N0136
START_カルテ詳細ボタンを押したとき --> N0150
START_カルテ編集ボタンを押したとき --> N0153
START_カルテ編集：既存患者タブを押したとき --> N0158
START_カルテ編集：新規患者タブを押したとき --> N0162
START_カルテ更新ボタンを押したとき --> N0166
START_カルテ削除ボタンを押したとき --> N0194
START_カルテ復活ボタンを押したとき --> N0204
START_保険請求書類を選択ボタンを押したとき --> N0214
START_書類ダウンロードボタンを押したとき --> N0221
START_印刷ボタンを押したとき --> N0232
START_患者マスタアイコンを押したとき --> N0240
START_患者マスタ新規登録ボタンを押したとき --> N0254
START_患者マスタ登録ボタンを押したとき --> N0259
START_患者マスタ詳細ボタンを押したとき --> N0287
START_患者マスタ編集ボタンを押したとき --> N0290
START_患者マスタ更新ボタンを押したとき --> N0295
START_患者マスタ削除ボタンを押したとき --> N0323
START_患者マスタ復活ボタンを押したとき --> N0333
START_アカウント管理アイコンを押したとき --> N0343
START_アカウント新規作成ボタンを押したとき --> N0357
START_アカウント登録ボタンを押したとき --> N0362
START_アカウント詳細ボタンを押したとき --> N0379
START_アカウント編集ボタンを押したとき --> N0382
START_アカウント更新ボタンを押したとき --> N0387
START_アカウント削除ボタンを押したとき --> N0404
START_アカウント復活ボタンを押したとき --> N0414
START_使用履歴ボタンを押したとき --> N0424
START_使用履歴詳細ボタンを押したとき --> N0432
class TITLE_01 textNode
class N0001 branchNode
class N0002 jumpNode
class N0003 jumpNode
class N0004 basicNode
class N0005 basicNode
class N0006 basicNode
class N0007 jumpNode
class N0008 basicNode
class N0009 basicNode
class N0010 branchNode
class N0011 sceneMoveNode
class N0012 sceneMoveNode
class TITLE_02 textNode
class N0013 branchNode
class N0014 jumpNode
class N0015 jumpNode
class N0016 basicNode
class N0017 branchNode
class N0018 jumpNode
class N0019 sceneMoveNode
class N0020 basicNode
class N0021 basicNode
class N0022 basicNode
class N0023 jumpNode
class TITLE_03 textNode
class N0024 basicNode
class N0025 basicNode
class N0026 branchNode
class N0027 sceneMoveNode
class N0028 jumpNode
class N0029 sceneMoveNode
class N0030 sceneMoveNode
class N0031 sceneMoveNode
class N0032 sceneMoveNode
class TITLE_04 textNode
class N0033 jumpNode
class TITLE_05 textNode
class N0034 basicNode
class N0035 basicNode
class N0036 sceneMoveNode
class N0037 sceneMoveNode
class N0038 sceneMoveNode
class N0039 sceneMoveNode
class N0040 sceneMoveNode
class N0041 sceneMoveNode
class N0042 sceneMoveNode
class N0043 sceneMoveNode
class TITLE_06 textNode
class N0044 basicNode
class N0045 basicNode
class N0046 sceneMoveNode
class TITLE_07 textNode
class N0047 basicNode
class N0048 basicNode
class N0049 branchNode
class N0050 sceneMoveNode
class N0051 sceneMoveNode
class TITLE_08 textNode
class N0052 basicNode
class N0053 basicNode
class N0054 sceneMoveNode
class TITLE_09 textNode
class N0055 basicNode
class N0056 jumpNode
class TITLE_10 textNode
class N0057 basicNode
class N0058 branchNode
class N0059 jumpNode
class N0060 jumpNode
class N0061 basicNode
class N0062 basicNode
class N0063 basicNode
class N0064 jumpNode
class N0065 basicNode
class N0066 jumpNode
class TITLE_11 textNode
class N0067 basicNode
class N0068 basicNode
class N0069 branchNode
class N0070 sceneMoveNode
class N0071 sceneMoveNode
class TITLE_12 textNode
class N0072 basicNode
class N0073 jumpNode
class TITLE_13 textNode
class N0074 branchNode
class N0075 jumpNode
class N0076 jumpNode
class N0077 basicNode
class N0078 branchNode
class N0079 jumpNode
class N0080 sceneMoveNode
class N0081 basicNode
class N0082 branchNode
class N0083 jumpNode
class N0084 jumpNode
class N0085 basicNode
class N0086 basicNode
class N0087 basicNode
class N0088 sceneMoveNode
class N0089 basicNode
class N0090 jumpNode
class TITLE_14 textNode
class N0091 basicNode
class N0092 basicNode
class N0093 branchNode
class N0094 sceneMoveNode
class N0095 sceneMoveNode
class TITLE_15 textNode
class N0096 basicNode
class N0097 basicNode
class N0098 basicNode
class N0099 basicNode
class N0100 branchNode
class N0101 sceneMoveNode
class N0102 sceneMoveNode
class TITLE_16 textNode
class N0103 basicNode
class N0104 basicNode
class N0105 branchNode
class N0106 sceneMoveNode
class N0107 sceneMoveNode
class TITLE_17 textNode
class N0108 branchNode
class N0109 jumpNode
class N0110 jumpNode
class N0111 jumpNode
class N0112 jumpNode
class N0113 basicNode
class N0114 branchNode
class N0115 jumpNode
class N0116 sceneMoveNode
class N0117 basicNode
class N0118 branchNode
class N0119 jumpNode
class N0120 sceneMoveNode
class N0121 basicNode
class N0122 basicNode
class N0123 branchNode
class N0124 jumpNode
class N0125 jumpNode
class N0126 basicNode
class N0127 branchNode
class N0128 jumpNode
class N0129 jumpNode
class N0130 basicNode
class N0131 jumpNode
class N0132 basicNode
class N0133 basicNode
class N0134 basicNode
class N0135 sceneMoveNode
class TITLE_18 textNode
class N0136 basicNode
class N0137 basicNode
class N0138 branchNode
class N0139 jumpNode
class N0140 sceneMoveNode
class N0141 basicNode
class N0142 basicNode
class N0143 basicNode
class N0144 branchNode
class N0145 sceneMoveNode
class N0146 sceneMoveNode
class N0147 sceneMoveNode
class N0148 sceneMoveNode
class N0149 sceneMoveNode
class TITLE_19 textNode
class N0150 basicNode
class N0151 basicNode
class N0152 jumpNode
class TITLE_20 textNode
class N0153 basicNode
class N0154 basicNode
class N0155 branchNode
class N0156 sceneMoveNode
class N0157 sceneMoveNode
class TITLE_21 textNode
class N0158 jumpNode
class N0159 branchNode
class N0160 sceneMoveNode
class N0161 jumpNode
class TITLE_22 textNode
class N0162 jumpNode
class N0163 branchNode
class N0164 sceneMoveNode
class N0165 jumpNode
class TITLE_23 textNode
class N0166 branchNode
class N0167 jumpNode
class N0168 jumpNode
class N0169 jumpNode
class N0170 jumpNode
class N0171 basicNode
class N0172 branchNode
class N0173 jumpNode
class N0174 sceneMoveNode
class N0175 basicNode
class N0176 branchNode
class N0177 jumpNode
class N0178 sceneMoveNode
class N0179 basicNode
class N0180 basicNode
class N0181 branchNode
class N0182 jumpNode
class N0183 jumpNode
class N0184 basicNode
class N0185 branchNode
class N0186 jumpNode
class N0187 jumpNode
class N0188 basicNode
class N0189 jumpNode
class N0190 basicNode
class N0191 basicNode
class N0192 basicNode
class N0193 jumpNode
class TITLE_24 textNode
class N0194 basicNode
class N0195 branchNode
class N0196 jumpNode
class N0197 jumpNode
class N0198 basicNode
class N0199 basicNode
class N0200 basicNode
class N0201 jumpNode
class N0202 basicNode
class N0203 jumpNode
class TITLE_25 textNode
class N0204 basicNode
class N0205 branchNode
class N0206 jumpNode
class N0207 jumpNode
class N0208 basicNode
class N0209 basicNode
class N0210 basicNode
class N0211 jumpNode
class N0212 basicNode
class N0213 jumpNode
class TITLE_26 textNode
class N0214 basicNode
class N0215 basicNode
class N0216 basicNode
class N0217 basicNode
class N0218 branchNode
class N0219 sceneMoveNode
class N0220 jumpNode
class TITLE_27 textNode
class N0221 basicNode
class N0222 branchNode
class N0223 jumpNode
class N0224 jumpNode
class N0225 basicNode
class N0226 basicNode
class N0227 branchNode
class N0228 sceneMoveNode
class N0229 jumpNode
class N0230 basicNode
class N0231 jumpNode
class TITLE_28 textNode
class N0232 basicNode
class N0233 branchNode
class N0234 jumpNode
class N0235 jumpNode
class N0236 basicNode
class N0237 jumpNode
class N0238 basicNode
class N0239 jumpNode
class TITLE_29 textNode
class N0240 basicNode
class N0241 basicNode
class N0242 branchNode
class N0243 jumpNode
class N0244 sceneMoveNode
class N0245 sceneMoveNode
class N0246 basicNode
class N0247 basicNode
class N0248 basicNode
class N0249 branchNode
class N0250 sceneMoveNode
class N0251 sceneMoveNode
class N0252 sceneMoveNode
class N0253 sceneMoveNode
class TITLE_30 textNode
class N0254 basicNode
class N0255 basicNode
class N0256 branchNode
class N0257 sceneMoveNode
class N0258 jumpNode
class TITLE_31 textNode
class N0259 branchNode
class N0260 jumpNode
class N0261 jumpNode
class N0262 jumpNode
class N0263 jumpNode
class N0264 basicNode
class N0265 branchNode
class N0266 jumpNode
class N0267 sceneMoveNode
class N0268 basicNode
class N0269 branchNode
class N0270 jumpNode
class N0271 sceneMoveNode
class N0272 basicNode
class N0273 basicNode
class N0274 branchNode
class N0275 jumpNode
class N0276 jumpNode
class N0277 basicNode
class N0278 branchNode
class N0279 jumpNode
class N0280 jumpNode
class N0281 basicNode
class N0282 jumpNode
class N0283 basicNode
class N0284 basicNode
class N0285 basicNode
class N0286 jumpNode
class TITLE_32 textNode
class N0287 basicNode
class N0288 basicNode
class N0289 jumpNode
class TITLE_33 textNode
class N0290 basicNode
class N0291 basicNode
class N0292 branchNode
class N0293 sceneMoveNode
class N0294 jumpNode
class TITLE_34 textNode
class N0295 branchNode
class N0296 jumpNode
class N0297 jumpNode
class N0298 jumpNode
class N0299 jumpNode
class N0300 basicNode
class N0301 branchNode
class N0302 jumpNode
class N0303 sceneMoveNode
class N0304 basicNode
class N0305 branchNode
class N0306 jumpNode
class N0307 sceneMoveNode
class N0308 basicNode
class N0309 basicNode
class N0310 branchNode
class N0311 jumpNode
class N0312 jumpNode
class N0313 basicNode
class N0314 branchNode
class N0315 jumpNode
class N0316 jumpNode
class N0317 basicNode
class N0318 jumpNode
class N0319 basicNode
class N0320 basicNode
class N0321 basicNode
class N0322 jumpNode
class TITLE_35 textNode
class N0323 basicNode
class N0324 branchNode
class N0325 jumpNode
class N0326 jumpNode
class N0327 basicNode
class N0328 basicNode
class N0329 basicNode
class N0330 jumpNode
class N0331 basicNode
class N0332 jumpNode
class TITLE_36 textNode
class N0333 basicNode
class N0334 branchNode
class N0335 jumpNode
class N0336 jumpNode
class N0337 basicNode
class N0338 basicNode
class N0339 basicNode
class N0340 jumpNode
class N0341 basicNode
class N0342 jumpNode
class TITLE_37 textNode
class N0343 basicNode
class N0344 basicNode
class N0345 branchNode
class N0346 jumpNode
class N0347 sceneMoveNode
class N0348 sceneMoveNode
class N0349 basicNode
class N0350 basicNode
class N0351 basicNode
class N0352 branchNode
class N0353 sceneMoveNode
class N0354 sceneMoveNode
class N0355 sceneMoveNode
class N0356 sceneMoveNode
class TITLE_38 textNode
class N0357 basicNode
class N0358 basicNode
class N0359 branchNode
class N0360 sceneMoveNode
class N0361 jumpNode
class TITLE_39 textNode
class N0362 branchNode
class N0363 jumpNode
class N0364 jumpNode
class N0365 basicNode
class N0366 branchNode
class N0367 jumpNode
class N0368 sceneMoveNode
class N0369 basicNode
class N0370 branchNode
class N0371 jumpNode
class N0372 jumpNode
class N0373 basicNode
class N0374 basicNode
class N0375 basicNode
class N0376 jumpNode
class N0377 basicNode
class N0378 jumpNode
class TITLE_40 textNode
class N0379 basicNode
class N0380 basicNode
class N0381 jumpNode
class TITLE_41 textNode
class N0382 basicNode
class N0383 basicNode
class N0384 branchNode
class N0385 sceneMoveNode
class N0386 jumpNode
class TITLE_42 textNode
class N0387 branchNode
class N0388 jumpNode
class N0389 jumpNode
class N0390 basicNode
class N0391 branchNode
class N0392 jumpNode
class N0393 sceneMoveNode
class N0394 basicNode
class N0395 branchNode
class N0396 jumpNode
class N0397 jumpNode
class N0398 basicNode
class N0399 basicNode
class N0400 basicNode
class N0401 jumpNode
class N0402 basicNode
class N0403 jumpNode
class TITLE_43 textNode
class N0404 basicNode
class N0405 branchNode
class N0406 jumpNode
class N0407 jumpNode
class N0408 basicNode
class N0409 basicNode
class N0410 basicNode
class N0411 jumpNode
class N0412 basicNode
class N0413 jumpNode
class TITLE_44 textNode
class N0414 basicNode
class N0415 branchNode
class N0416 jumpNode
class N0417 jumpNode
class N0418 basicNode
class N0419 basicNode
class N0420 basicNode
class N0421 jumpNode
class N0422 basicNode
class N0423 jumpNode
class TITLE_45 textNode
class N0424 basicNode
class N0425 basicNode
class N0426 branchNode
class N0427 jumpNode
class N0428 sceneMoveNode
class N0429 basicNode
class N0430 basicNode
class N0431 sceneMoveNode
class TITLE_46 textNode
class N0432 basicNode
class N0433 basicNode
class N0434 jumpNode
class START_システムを開いたとき textNode
class START_ログインボタンを押したとき textNode
class START_ホーム画面の各アイコンを押したとき（呼び出し元：システムを開いたとき） textNode
class START_ホーム画面の各アイコンを押したとき（呼び出し元：ログインボタンを押したとき） textNode
class START_ハンバーガーメニューを押したとき textNode
class START_利用規約ボタンを押したとき（呼び出し元：ログイン画面） textNode
class START_ログイン画面に戻るボタンを押したとき textNode
class START_利用規約ボタンを押したとき（呼び出し元：ハンバーガーメニュー） textNode
class START_ハンバーガーメニューに戻るボタンを押したとき textNode
class START_ログアウトボタンを押したとき textNode
class START_ログイン情報変更ボタンを押したとき textNode
class START_ホーム画面に戻るボタンを押したとき textNode
class START_ログイン情報変更の変更するボタンを押したとき textNode
class START_カルテ新規入力アイコンを押したとき textNode
class START_カルテ新規入力：既存患者タブを押したとき textNode
class START_カルテ新規入力：新規患者タブを押したとき textNode
class START_カルテ登録ボタンを押したとき textNode
class START_カルテ検索アイコンを押したとき textNode
class START_カルテ詳細ボタンを押したとき textNode
class START_カルテ編集ボタンを押したとき textNode
class START_カルテ編集：既存患者タブを押したとき textNode
class START_カルテ編集：新規患者タブを押したとき textNode
class START_カルテ更新ボタンを押したとき textNode
class START_カルテ削除ボタンを押したとき textNode
class START_カルテ復活ボタンを押したとき textNode
class START_保険請求書類を選択ボタンを押したとき textNode
class START_書類ダウンロードボタンを押したとき textNode
class START_印刷ボタンを押したとき textNode
class START_患者マスタアイコンを押したとき textNode
class START_患者マスタ新規登録ボタンを押したとき textNode
class START_患者マスタ登録ボタンを押したとき textNode
class START_患者マスタ詳細ボタンを押したとき textNode
class START_患者マスタ編集ボタンを押したとき textNode
class START_患者マスタ更新ボタンを押したとき textNode
class START_患者マスタ削除ボタンを押したとき textNode
class START_患者マスタ復活ボタンを押したとき textNode
class START_アカウント管理アイコンを押したとき textNode
class START_アカウント新規作成ボタンを押したとき textNode
class START_アカウント登録ボタンを押したとき textNode
class START_アカウント詳細ボタンを押したとき textNode
class START_アカウント編集ボタンを押したとき textNode
class START_アカウント更新ボタンを押したとき textNode
class START_アカウント削除ボタンを押したとき textNode
class START_アカウント復活ボタンを押したとき textNode
class START_使用履歴ボタンを押したとき textNode
class START_使用履歴詳細ボタンを押したとき textNode
style SG01 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG02 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG03 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG04 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG05 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG06 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG07 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG08 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG09 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG10 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG11 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG12 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG13 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG14 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG15 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG16 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG17 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG18 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG19 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG20 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG21 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG22 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG23 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG24 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG25 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG26 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG27 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG28 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG29 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG30 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG31 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG32 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG33 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG34 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG35 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG36 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG37 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG38 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG39 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG40 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG41 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG42 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG43 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG44 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG45 fill:#f2f2f2,stroke:#333,stroke-width:2px
style SG46 fill:#f2f2f2,stroke:#333,stroke-width:2px